routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('register', function(){
    return redirect('/login');
});
Auth::routes(['register' => false]);
Auth::routes();
Route::middleware(['auth:web'])->group(function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    //user
    Route::resource('/users', 'UserController');
    Route::get('/user/status/{id}', 'UserController@status');
    #UserProfile Routes
    Route::resource('profile','ProfileController');
    Route::post('/update-password','ProfileController@updatePassword')->name('update-password');
    //departments
    Route::resource('/departments', 'DepartmentController');
    Route::get('/departments/status/{id}', 'DepartmentController@status');
    //roles
    Route::resource('/roles', 'RoleController');
    Route::get('/roles/status/{id}', 'RoleController@status');
    //permissions
    Route::resource('/permissions', 'PermissionController');
    Route::get('/permissions/status/{id}', 'PermissionController@status');
    // jobtype
    Route::resource('/jobtype', 'JobTypeController');
    Route::get('/getOptions', 'JobTypeController@getOptions')->name('getOptions');
    Route::get('/getInputs', 'JobTypeController@getInputs')->name('getInputs');
    Route::get('/getTypes', 'JobTypeController@getTypes')->name('getTypes');
    Route::get('/getJobTypes', 'JobTypeController@getJobTypes')->name('getJobTypes');
    //department
    Route::resource('/departments', 'DepartmentController');
    Route::get('/departments/status/{id}', 'DepartmentController@status');
    //company
    Route::resource('/companies', 'CompanyController');
    Route::get('/company/status/{id}', 'CompanyController@status');
    Route::get('/company/portfolio/delete', 'CompanyController@deletePortfolio')->name('deletePortfolio');
    //jobs
    Route::resource('/jobs', 'JobController');
    Route::get('/job/status/{id}', 'JobController@status');
    Route::get('/getJobtype', 'JobController@departmentJobType')->name('getJobType');
    Route::get('/getStaff', 'JobController@departmentStaff')->name('getStaff');
    Route::get('/getManager', 'JobController@departmentManager')->name('getManager');
    Route::get('/completeJob', 'JobController@CompleteJob')->name('CompleteJob');
    Route::get('/assignedJob', 'JobController@AssignedJob')->name('AssignedJob');
    //job workflow
    Route::resource('/job-workflow', 'JobWorkflowController');
    //job output
    Route::resource('/job-output', 'JobOutputController');
    Route::get('/download/{id}', 'JobOutputController@getDownload');
    Route::get('/output-file/{id}', 'JobOutputController@pdfView')->name('output-file');
    //job recurrence
    Route::resource('/recurrence', 'RecurrenceController');
    // settings
    Route::resource('/settings', 'SettingController');
    Route::get('/setting/delete', 'SettingController@deleteSetting')->name('deleteSetting');
    
    // approval
    Route::resource('/approvals', 'ApprovalController');
    // invoice
    Route::resource('/invoices', 'InvoiceController');
    Route::get('/invoices-generate/{jobId}/{jobTypeWorkflow}/{workflowType}/{workflowOption}/{jobWorkflow?}','JobWorkflowController@invoiceGenerate')->name('invoices.generate');
    Route::post('/invoice/items/edit/{id}', 'InvoiceController@InvoiceItemEdit')->name('invoiceItem.edit');
    Route::get('/getJobs', 'InvoiceController@getCompanyJobs')->name('getJobs');
    Route::get('/getSettings', 'InvoiceController@getSettings')->name('getSettings');
    Route::get('/invoices/status/{id}', 'InvoiceController@status');
    Route::get('download-invoice/{id}','InvoiceController@downloadInvoice');
    Route::get('invoice-preview/{id}','InvoiceController@previewInvoice');
    Route::get('payment/{id}','InvoiceController@payment');
    Route::resource('/payments', 'PaymentController');
    // Notifications web routes
    Route::resource('/notifications', 'NotificationController');
    Route::get('notifications-{filter}', 'NotificationController@index')->name('notifications');
    Route::get('notification-markallasread', 'NotificationController@mark_all_as_read')->name('markAllRead');;
    Route::get('notification-markasread-{id}', 'NotificationController@mark_as_read');
    Route::get('notification-markasunread-{id}', 'NotificationController@mark_as_unread');
    Route::get('notification-delete-{id}', 'NotificationController@delete');
});

resources/views/billings/create.blade.php
@extends('layouts.app', [
'activePage' => 'create-invoice',
'menuParent' => 'create-invoice',
'title' => 'Create Invoice',
])
@section('content')

<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Billing<small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted"></small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item"><a href="{{ route('invoices.index') }}">Billing</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx text-black">Create</a>
                    </li>
                </ol>
            </nav>

        </div>
    </div>
</div>
<!-- Page Content -->
<div class="content">

    <!-- Alternative Style -->
    <div class="block block-rounded">
        <ul class="nav nav-tabs nav-tabs-block" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-home">General</a>
            </li>
        </ul>
        <form action="{{ route('invoices.store') }}" method="POST">
            @csrf
            <div class="block-content tab-content">
                <div class="tab-pane active" id="btabs-home" role="tabpanel">

                    <div class="block-content block-content-full">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="company">Customer<span class="text-danger">*</span></label>
                                    <select class="company form-control @error('company_id') is-invalid @enderror" id="company_id" name="company_id" style="width: 100%;" data-placeholder="Choose" readonly="readonly">
                                        <option value="">{{__('Please Select')}}</option>
                                        @foreach($companies as $company)
                                        <option value="{{ $company->id }}" @if ($company->id == old('company_id')) selected @endif>{{ $company->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('company_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="job">Jobs</label>
                                    <select id="jobs" class="js-select2 form-control @error('job_id') is-invalid @enderror" id="job_id" name="job_id" style="width: 100%;" data-placeholder="Choose">
                                        <option disabled selected>Select</option> 
                                        @if(!empty(old('company_id')))
                                        @php
                                        $jobs = \App\Models\Jobs\Job::with('job_type')->where('company_id', old('company_id'))->where('status',1)->get();
                                        @endphp
                                        @foreach($jobs as $job)
                                        <option value="{{ $job->id }}" @if($job->id == old('job_id')) selected @endif>{{$job->job_type->name }}</option>
                                        @endforeach 
                                        @endif
                                    </select>
                                    @error('job_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="department">Departments<span class="text-danger">*</span></label>
                                    <select class="js-select2 form-control @error('department_id') is-invalid @enderror" id="department_id" name="department_id" style="width: 100%;" data-placeholder="Choose">
                                        <option value="">{{__('Please Select')}}</option>
                                        @foreach($departments as $department)
                                        <option value="{{ $department->id }}" @if ($department->id == old('department_id')) selected @endif>{{ $department->name }}</option>
                                        @endforeach
                                    </select>
                                    @error('department_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="name">Bill From:<span class="text-danger">*</span></label>
                                    <select class="js-select2 form-control @error('setting_id') is-invalid @enderror" id="setting_id" name="setting_id" style="width: 100%;" data-placeholder="Choose">
                                        <option value="">{{__('Please Select')}}</option>
                                        @if(!empty(old('department_id')))
                                        @php
                                        $settings = \App\Models\Setting::where('department_id', old('department_id'))->get();
                                        @endphp
                                        @foreach($settings as $setting)
                                        <option value="{{ $setting->id }}" @if ($setting->id == old('setting_id')) selected @endif>{{ $setting->name }}</option>
                                        @endforeach
                                        @endif
                                    </select>
                                    @error('setting_id')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="amount">Amount Due:<span class="text-danger">*</span></label>
                                    <input type="text" class="form-control @error('amount') is-invalid @enderror" id="amount" name="amount" value="{{old('amount')}}" placeholder="Amount">
                                    @error('amount')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="invoiceDate">Invoice Date:<span class="text-danger">*</span></label>
                                    <input type="date" class="form-control @error('invoiceDate') is-invalid @enderror" id="invoiceDate" name="invoiceDate" value="{{old('invoiceDate')}}" placeholder="invoiceDate">
                                    @error('invoiceDate')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="dueDate">Due Date:<span class="text-danger">*</span></label>
                                    <input type="date" class="form-control @error('dueDate') is-invalid @enderror" id="dueDate" name="dueDate" value="{{old('dueDate')}}" placeholder="dueDate">
                                    @error('dueDate')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="debtorCode">Debtor A/C code:</label>
                                    <input type="text" class="form-control @error('debtorCode') is-invalid @enderror" id="debtorCode" name="debtorCode" value="{{old('debtorCode')}}" placeholder="Debtor A/C Code">
                                    @error('debtorCode')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="form-group">
                                    <label for="description">Description</label>
                                    <textarea type="text" class="form-control @error('description') is-invalid @enderror" id="description" name="description" value="{{old('description')}}" placeholder="description">{{old('description')}}</textarea>
                                    @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </form>

    </div>

</div>
<!-- END Alternative Style -->

<!-- END Page Content -->
@endsection
@push('scripts')
<script type="text/javascript">
    // CSRF Token
    var CSRF_TOKEN = $('meta[name="csrf-token"]').attr('content');
    $(document).ready(function () {
        var companyId = '';
        $(document).on('change', '.company', function () {
            var companyId = $(this).val();
            $('#jobs').empty();
            $.ajax({
                type: 'get'
                , url: "{{route('getJobs')}}"
                , data: 'company=' + companyId
                , success: function (data) {
                    var html = '<option disabled selected value="">Select</option>';
                    html += data;
                    $('#jobs').html(html);
                }
            });
        });
        $(document).on('change', '#department_id', function () {
            var departmentId = $(this).val();

            $('#setting_id').empty();
            $.ajax({
                type: 'get'
                , url: "{{route('getSettings')}}"
                , data: 'department=' + departmentId
                , success: function (data) {
                    var html = '<option disabled selected value="">Select</option>';
                    html += data;
                    $('#setting_id').html(html);
                }
            });
        });
    });

</script>
@endpush

resources/views/billings/index.blade.php
@extends('layouts.app', [
'activePage' => 'billings',
'menuParent' => 'billings',
'title' => 'Billings',
])
@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="row d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <div class="col-sm-8 d-flex justify-content-start align-items-center">
                <h1 class="flex-sm-00-auto h3 my-2">
                    Billings <small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted"></small>
                </h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Billings</li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="text-black text-muted">List</a>
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-4">
                @can('invoice_create')
                <div class="text-right">
                    <a href="{{ route('invoices.create') }}" class="btn btn-primary">Create</a>
                </div>
                @endcan
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->
<!-- Page Content -->
<div class="content">
    <!-- Dynamic Table with Export Buttons -->
    <div class="block block-rounded">
        <div class="block-content block-content-full">
            <form action="" method="GET">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="form-group">
                            <select class="form-control" name="department">
                                <option disabled selected>Select Department</option>
                                @foreach($departments as $key => $department)
                                <option value="{{ $department->id }}" @if($department->id == Request::get('department')) selected @endif>{{ $department->name }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <select class="form-control" name="status">
                                <option selected value="">Select</option>
                                <option value="0" @if (Request::get('status') == 0 ) selected @endif>Unpaid </option>
                                <option value="1" @if (Request::get('status') == 1) selected @endif>Paid </option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-3">
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Filters</button>
                            <a href="{{ route('invoices.index') }}" class="btn btn-danger">Clear All</a>
                        </div>
                    </div>
                </div>
            </form>
            <table class="table table-bordered table-striped table-vcenter js-dataTable-full font-size-sm">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 10px;">#</th>
                        <th>CUSTOMER</th>
                        <th>BILL NO.</th>
                        <th>DUE</th>
                        <th class="d-none d-sm-table-cell text-center" style="width: 12%;">DATE</th>
                        <th style="width: 15%;">AMOUNT DUE</th>
                        <th class="text-center">STATUS</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($invoices as $key => $invoice)
                    <tr>
                        <td class="text-center">{{$key+1}}</td>
                        <td class="font-w600">
                            <a href="{{ route('invoices.show',$invoice->id) }}">{{ ucwords($invoice->company->name) }}</a>
                        </td>
                        <td class="font-w500">
                            <span class="text-muted">{{ $invoice->invoice_no }}</span>
                        </td>
                        <td class="font-w500">
                            <span class="text-muted">{{\Carbon\Carbon::parse($invoice->due_date)->format('Y-m-d')}}</span>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <span class="text-muted">{{\Carbon\Carbon::parse($invoice->invoice_date)->format('Y-m-d')}}</span>
                        </td>
                        <td class="text-center">
                            <span class="font-weight-bold">{{ config('app.currency_code') }} {{ number_format(round($invoice->total_amount,2), 2, '.', '') }}</span>
                        </td>
                        <td class="d-none d-sm-table-cell text-center font-size-lg">
                            @if ($invoice->status == 1)
                            <span class="badge badge-pill badge-status badge-success">Paid</span>
                            @elseif (\Carbon\Carbon::parse($invoice->due_date)->format('Y-m-d') < \Carbon\Carbon::now()->format('Y-m-d'))
                            <span class="badge badge-pill badge-status badge-danger">Overdue</span>
                            @elseif ($invoice->status == 0)
                            <span class="badge badge-pill badge-status badge-warning">Pending</span>
                            @endif
                        </td>
                        <td class="text-center">
                            <div class="btn-group">
                                @can('invoice_edit')
                                <a class="btn btn-sm btn-light" href="{{ route('invoices.show', $invoice->id) }}"><i class="nav-main-link-icon fa fa-edit"></i></a>
                                @endcan
                                @can('invoice_delete')
                                <form action="{{ route('invoices.destroy',$invoice->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-sm btn-light delete" data-name="{{ $invoice->company->name }}"
                                            title="{{__('Delete')}}">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                                @endcan
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>

    </div>
</div>
<!-- END Dynamic Table with Export Buttons -->
</div>
<!-- END Page Content -->
@endsection

resources/views/billings/payment.blade.php
@extends('layouts.app', [
'activePage' => 'payment',
'menuParent' => 'payment',
'title' => 'Payment',
])
@section('content')

<div class="bg-body-light">
    <div class="content content-full">
        <div class="d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <h1 class="flex-sm-fill h3 my-2">
                Payment<small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted"></small>
            </h1>
            <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                <ol class="breadcrumb breadcrumb-alt">
                    <li class="breadcrumb-item"><a href="{{ route('invoices.index') }}">Payment</a></li>
                    <li class="breadcrumb-item" aria-current="page">
                        <a class="link-fx text-black">Create</a>
                    </li>
                </ol>
            </nav>

        </div>
    </div>
</div>
<!-- Page Content -->
<div class="content">
    <!-- Alternative Style -->
    <div class="block block-rounded">

        <form action="{{route('payments.store')}}" method="POST">
            @csrf

            <div class="block-content block-content-full">
                <div class="row">
                    <input type="hidden" name="invoice_id" value="{{$id}}">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="department">Payment Note</label>
                            <input type="text"  class="form-control form-control-alt @error('debtorCode') is-invalid @enderror" id="payment_note" name="payment_note" value="{{old('payment_note')}}" placeholder="Payment Note" >
                            @error('payment_note')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="name">Amount<span class="text-danger">*</span></label>
                            <input type="text"  class="form-control form-control-alt @error('amount') is-invalid @enderror" id="amount" name="amount" value="{{old('amount')}}" placeholder="amount" >
                            @error('amount')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="debtorCode">Description</label>
                            <textarea type="text"  class="form-control form-control-alt @error('description') is-invalid @enderror" id="description" name="description" value="{{old('description')}}" placeholder="description" >{{old('description')}}</textarea>
                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                            @enderror
                        </div>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
    </div>
</div>
@endsection