routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('register', function(){
    return redirect('/login');
});
Auth::routes(['register' => false]);
Auth::routes();
Route::middleware(['auth:web'])->group(function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    //user
    Route::resource('/users', 'UserController');
    Route::get('/user/status/{id}', 'UserController@status');
    #UserProfile Routes
    Route::resource('profile','ProfileController');
    Route::post('/update-password','ProfileController@updatePassword')->name('update-password');
    //departments
    Route::resource('/departments', 'DepartmentController');
    Route::get('/departments/status/{id}', 'DepartmentController@status');
    //roles
    Route::resource('/roles', 'RoleController');
    Route::get('/roles/status/{id}', 'RoleController@status');
    //permissions
    Route::resource('/permissions', 'PermissionController');
    Route::get('/permissions/status/{id}', 'PermissionController@status');
    // jobtype
    Route::resource('/jobtype', 'JobTypeController');
    Route::get('/getOptions', 'JobTypeController@getOptions')->name('getOptions');
    Route::get('/getInputs', 'JobTypeController@getInputs')->name('getInputs');
    Route::get('/getTypes', 'JobTypeController@getTypes')->name('getTypes');
    Route::get('/getJobTypes', 'JobTypeController@getJobTypes')->name('getJobTypes');
    //department
    Route::resource('/departments', 'DepartmentController');
    Route::get('/departments/status/{id}', 'DepartmentController@status');
    //company
    Route::resource('/companies', 'CompanyController');
    Route::get('/company/status/{id}', 'CompanyController@status');
    Route::get('/company/portfolio/delete', 'CompanyController@deletePortfolio')->name('deletePortfolio');
    //jobs
    Route::resource('/jobs', 'JobController');
    Route::get('/job/status/{id}', 'JobController@status');
    Route::get('/getJobtype', 'JobController@departmentJobType')->name('getJobType');
    Route::get('/getStaff', 'JobController@departmentStaff')->name('getStaff');
    Route::get('/getManager', 'JobController@departmentManager')->name('getManager');
    Route::get('/completeJob', 'JobController@CompleteJob')->name('CompleteJob');
    Route::get('/assignedJob', 'JobController@AssignedJob')->name('AssignedJob');
    //job workflow
    Route::resource('/job-workflow', 'JobWorkflowController');
    //job output
    Route::resource('/job-output', 'JobOutputController');
    Route::get('/download/{id}', 'JobOutputController@getDownload');
    Route::get('/output-file/{id}', 'JobOutputController@pdfView')->name('output-file');
    //job recurrence
    Route::resource('/recurrence', 'RecurrenceController');
    // settings
    Route::resource('/settings', 'SettingController');
    Route::get('/setting/delete', 'SettingController@deleteSetting')->name('deleteSetting');
    
    // approval
    Route::resource('/approvals', 'ApprovalController');
    // invoice
    Route::resource('/invoices', 'InvoiceController');
    Route::get('/invoices-generate/{jobId}/{jobTypeWorkflow}/{workflowType}/{workflowOption}/{jobWorkflow?}','JobWorkflowController@invoiceGenerate')->name('invoices.generate');
    Route::post('/invoice/items/edit/{id}', 'InvoiceController@InvoiceItemEdit')->name('invoiceItem.edit');
    Route::get('/getJobs', 'InvoiceController@getCompanyJobs')->name('getJobs');
    Route::get('/getSettings', 'InvoiceController@getSettings')->name('getSettings');
    Route::get('/invoices/status/{id}', 'InvoiceController@status');
    Route::get('download-invoice/{id}','InvoiceController@downloadInvoice');
    Route::get('invoice-preview/{id}','InvoiceController@previewInvoice');
    Route::get('payment/{id}','InvoiceController@payment');
    Route::resource('/payments', 'PaymentController');
    // Notifications web routes
    Route::resource('/notifications', 'NotificationController');
    Route::get('notifications-{filter}', 'NotificationController@index')->name('notifications');
    Route::get('notification-markallasread', 'NotificationController@mark_all_as_read')->name('markAllRead');;
    Route::get('notification-markasread-{id}', 'NotificationController@mark_as_read');
    Route::get('notification-markasunread-{id}', 'NotificationController@mark_as_unread');
    Route::get('notification-delete-{id}', 'NotificationController@delete');
});

app/Models/Company/CompanyAccountResponsible.php
<?php

namespace App\Models\Company;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CompanyAccountResponsible extends Model
{
    use HasFactory,SoftDeletes;
    protected $table        = 'company_account_responsibles';
    protected $dates        = ['created_at','updated_at','deleted_at'];
    protected $fillable     = ['company_id','name','department_id'];
    /**
    * Get all of the departments.
    */
    public function departments()
    {
        return $this->belongsTo('App\Models\Users\Department', 'department_id');
    }
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // relation
    public function company()
    {
        return $this->belongsTo('App\Models\Company\Company', 'company_id');
    }
}

app/Models/Company/CompanyAddress.php
<?php

namespace App\Models\Company;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CompanyAddress extends Model
{
    use HasFactory,SoftDeletes;
    protected $table    = 'company_addresses';
    protected $dates    = ['created_at','updated_at','deleted_at'];
    protected $fillable = ['company_id','addresse_type','name','phone','address',];
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // relation
    public function company()
    {
        return $this->belongsTo('App\Models\Company\Company', 'company_id');
    }
}

app/Models/Company/CompanyDocument.php
<?php

namespace App\Models\Company;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CompanyDocument extends Model
{
    use HasFactory,SoftDeletes;
    protected $table = 'company_documents';
    protected $dates = ['created_at','updated_at','deleted_at'];
    protected $fillable = ['company_id','report_type','report_year','receive_date','submited'];
    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    // relation
    public function company()
    {
        return $this->belongsTo('App\Models\Company\Company', 'company_id');
    }
}

app/Models/Company/CompanyINCharge.php
<?php

namespace App\Models\Company;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CompanyINCharge extends Model
{
    use HasFactory,SoftDeletes;
    protected $table  = 'company_incharge';
    protected $dates  = ['created_at','updated_at','deleted_at'];
    protected $fillable = ['company_id','department_id','name','phone','email',];
   /**
    * Get all of the departments.
    */
    public function departments()
    {
        return $this->belongsTo('App\Models\Users\Department', 'department_id');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
#models
use App\Models\Users\User;
use App\Models\Users\Department;
use App\Models\Company\Company;
use App\Models\Company\CompanyAddress;
use App\Models\Company\CompanyINCharge;
use App\Models\Company\RelatedCompany;
use App\Models\Company\CompanyShare;
use App\Models\Company\CompanyAccountResponsible;
use App\Models\Company\CompanyPortfolio;
use App\Models\Company\CompanyDocument;
use App\Models\Company\CompanyPayment;
use App\Models\Company\Invoice;
use App\Models\Company\CompanyReminder;
#request
use App\Http\Requests\CompanyStoreRequest;
use App\Http\Requests\CompanyUpdateRequest;

#classes
use Validator, Session, Hash;

class CompanyController extends Controller
{
    
    function __construct() {
        $this->middleware('permission:company_access|company_create|company_edit|company_delete|company_status', ['only' => ['index', 'show']]);
        $this->middleware('permission:company_create', ['only' => ['create', 'store']]);
        $this->middleware('permission:company_edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:company_delete', ['only' => ['destroy']]);
        $this->middleware('permission:company_status', ['only' => ['status']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::orderBy('created_at', 'DESC')->get();
        return view('companies.index',compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::where('status',1)->get();
        $documentType = [0 => 'Annual Return',1 => 'Audit Report to SSM',2 => 'Audit Report to Tax Department'];
        return view('companies.create',compact('departments','documentType'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyStoreRequest $request)
    { 
        //check validations
        $validator = $request->validated();
        // store data
        $company = new Company();
        $company->name         = $request->name;
        $company->email        = $request->email;
        $company->company_fak  = $request->company_fka;
        $company->roc          = $request->company_roc;
        $company->incorporation_date    = $request->incorporation_date;
        $company->e_no          = $request->e_no;
        $company->c_no          = $request->c_no;
        $company->natureof_business = $request->natureof_business;
        $company->phone_no      = $request->phone;
        $company->fax_no        = $request->fax;
        $company->bank_name     = $request->bank_name;
        $company->account_no    = $request->account_number;
        $company->financial_year_end     = $request->financial_year_end;
        $company->annual_return_date     = $request->annual_return_date;
        $company->turnover      = $request->turnover;
        $company->profit_before_tax     = $request->profit_before_tax;
        $company->annual_meeting_date   = $request->annual_meeting_date;
        $company->ep_certificate        = $request->ep_certificate;
        $company->date_of_change       = $request->date_of_change;
        if($request->extension_time == 'Yes'){
          $company->applied_date          = $request->new_due_date;  
        }else{
          $company->applied_date          = $request->applied_date;  
        }
        // $company->applied_date          = $request->applied_date;
        $company->new_due_date          = $request->new_due_date;
        $company->extension_time        = $request->extension_time;
//        $company->company_etr           = $request->company_etr;
//        $company->etr_date              = $request->etr_date;
        $company->status_date           = $request->status_date;
        $company->status                = 1;
        $company->acitivity_status      = $request->activity_status;
        $company->contact               = $request->contact;
        $company->save();
        // company addresses
        foreach ($request->address_type as $key => $addressType) {
            $companyAddress = new CompanyAddress();
            $companyAddress->company_id    = $company->id;
            $companyAddress->addresse_type = $addressType;
            $companyAddress->name          = $request->address_name[$key];
            $companyAddress->phone         = $request->address_phone[$key];
            $companyAddress->address       = $request->address[$key];
            $companyAddress->save();
        }
        // company incharge
        if (isset($request->incharge_name)) {
            foreach ($request->incharge_name as $key => $name) {
                $companyInCharge = new CompanyINCharge();
                $companyInCharge->company_id    = $company->id;
                $companyInCharge->department_id    =$request->incharge_department_id[$key];
                $companyInCharge->name          = $name;
                $companyInCharge->phone         = $request->incharge_phone[$key];
                $companyInCharge->email         = $request->incharge_email[$key];
                $companyInCharge->save();
            }
        }
        // company responsible
        if (isset($request->responsible_name)) {
            foreach ($request->responsible_name as $key => $name) {
                $companyResponsilbe = new CompanyAccountResponsible();
                $companyResponsilbe->company_id    = $company->id;
                $companyResponsilbe->department_Id = $key;
                $companyResponsilbe->name          = json_encode($name,true);
                $companyResponsilbe->save();
            }
        }
        // company shareholder
        if (isset($request->shareholder_name) && isset($request->values)) {
            $labels = $request->shareholder_name;
            $values = $request->values;
            $array = array_combine($labels, $values);
            $json = json_encode($array,true);
        }else {
            $labels = [''];
            $values = [''];
            $array = array_combine($labels, $values);
            $json = json_encode([],true);
        }
        if (isset($request->director)) {
            $directorJson = json_encode($request->director,true);
        }else {
            $directorJson = json_encode([],true);
        }
        // company shares
        $companyShare = new CompanyShare();
        $companyShare->company_id       = $company->id;
        $companyShare->share_capital    = $request->share_capital;
        $companyShare->shareholder_name = $json;
        $companyShare->shareholder_updated_on = $request->shareholder_updated_on;
        $companyShare->director         = $directorJson;
        $companyShare->director_updated_on = $request->director_updated_on;
        $companyShare->save();
        // relatable company
        if (isset($request->groupof_companies)) {
            $relatedCompany = new RelatedCompany();
            $relatedCompany->company_id    = $company->id;
            $relatedCompany->name          = json_encode($request->groupof_companies,true);
            $relatedCompany->save();
        }
        // company document
        if (isset($request->document_type)) {
            foreach ($request->document_type as $key => $item) {
                if(isset($item['report_year']) || isset($item['recevie_date']) || isset($item['submitted'])){
                    $report_year = json_encode($item['report_year'],true);
                    $recevie_date = json_encode($item['recevie_date'],true);
                    $submitted = json_encode($item['submitted'],true);
                }else{
                    $report_year = json_encode([],true);
                    $recevie_date = json_encode([],true);
                    $submitted = json_encode([],true);
                }
                $companyDocument = new CompanyDocument();
                $companyDocument->company_id    = $company->id;
                $companyDocument->report_type   = $item['type'];
                $companyDocument->report_year   = $report_year;
                $companyDocument->receive_date  = $recevie_date;
                $companyDocument->submited      = $submitted ;
                $companyDocument->save();
            }
        }
        // company portfolio
        if (isset($request->company_portfolio)) {
            foreach ($request->company_portfolio as $key1 => $item) {
                if (isset($item['user_id']) || count($item['user_id']) > 0) {
                    foreach($item['user_id'] as $key => $userId){
                        if($userId != null){
                        $companyPortfolio = new CompanyPortfolio();
                        $companyPortfolio->company_id    = $company->id;
                        $companyPortfolio->department_id = $item['department_id'];
                        $companyPortfolio->user_id       = $userId;
                        $companyPortfolio->date          =  $item['date'][$key];
                        $companyPortfolio->save();
                        }
                    }
                }
            }
        }
        // company reminder
       
                $company_reminder = new CompanyReminder();
                $company_reminder->company_id = $company->id;
                $company_reminder->secretarialFees = isset($request->company_reminder['secretarialfees']) ? $request->company_reminder['secretarialfees'] : 0;
                $company_reminder->is_annualReturn_notify = isset($request->company_reminder['annualReturn']) ?$request->company_reminder['annualReturn'] : 0;

resources/views/companies/index.blade.php
@extends('layouts.app', [
'activePage' => 'customers-list',
'menuParent' => 'customers-list',
'title' => 'Customers',
])
@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="row d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <div class="col-sm-8 d-flex justify-content-start align-items-center">
                <h1 class="flex-sm-00-auto h3 my-2">
                    Customers <small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted"></small>
                </h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Customers</li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="text-black text-muted">List</a>
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-4">
                @can('company_create')
                <div class="text-right">
                    <a href="{{ route('companies.create') }}" class="btn btn-primary">Create</a>
                </div>
                @endcan
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->
<!-- Page Content -->
<div class="content">
    <!-- Dynamic Table with Export Buttons -->
    <div class="block block-rounded">
        <div class="block-content block-content-full">
            <!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized in js/pages/tables_datatables.js -->
            <table class="table table-bordered table-striped table-vcenter js-dataTable-full  font-size-sm" id="example">
                <thead>
                    <tr>
                        <th class="text-center" style="width: 10px;">#</th>
                        <th>Customer Name</th>
                        <th class="d-none d-sm-table-cell">Email</th>
                        <th style="width: 20%;">Contact Number</th>
                        <th class="" style="width: 15%;">Activity Status</th>
                        <th class="text-center" style="width:145px;">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($companies as $key => $company)
                    <tr>
                        <td class="text-center">{{ $key +1 }}</td>
                        <td class="font-w600">
                            <a href="{{ route('companies.show',$company->id) }}">{{ ucwords($company->name) }}</a>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <span class="text-muted">{{ $company->email }}</span>
                        </td>
                        <td>
                            <span class="text-muted">{{ $company->phone_no }}</span>
                        </td>
                        <td class="">
                            @if($company->acitivity_status == 1)
                            <span class="badge  badge-success">Super Active</span>
                            @elseif($company->acitivity_status == 2)
                            <span class="badge  badge-primary">Active</span>
                            @elseif($company->acitivity_status == 3)
                            <span class="badge badge-info">Semi Active</span>
                            @elseif($company->acitivity_status == 4)
                            <span class="badge  badge-danger">Dormant</span>
                            @elseif($company->acitivity_status == 5)
                            <span class="badge  badge-dark">Winding Up</span>
                            @elseif($company->acitivity_status == 6)
                            <span class="badge  badge-warning">Striking Off</span> 
                            @endif
                        </td>
                        <td class="font-w600 text-center">
                            <div class="btn-group">
                                @can('company_edit')    
                                <a class="btn btn-sm btn-light" href="{{ route('companies.edit',$company->id) }}"><i class="fa fa-edit"></i></a>
                                @endcan
                                @can('company_delete')
                                <form action="{{ route('companies.destroy', $company->id) }}" method="POST" >
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                    <button data-name="{{ $company->name }}" type="submit" class="btn btn-sm btn-light delete"><i class="fa fa-trash"></i></button>
                                </form>
                                @endcan
                                @can('company_status')
                                @if($company->status == 1)
                                <a href="{{url('company/status/'.$company->id)}}" class="btn btn-sm btn-light" title="active"><i class="fa fa-unlock"></i></a>
                                @else
                                <a href="{{url('company/status/'.$company->id)}}" class="btn btn-sm btn-light" title="Inactive"><i class="fa fa-lock"></i></a>
                                @endif
                                @endcan
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Dynamic Table with Export Buttons -->
</div>
<!-- END Page Content -->
@endsection