routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('register', function(){
    return redirect('/login');
});
Auth::routes(['register' => false]);
Auth::routes();
Route::middleware(['auth:web'])->group(function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    //user
    Route::resource('/users', 'UserController');
    Route::get('/user/status/{id}', 'UserController@status');
    #UserProfile Routes
    Route::resource('profile','ProfileController');
    Route::post('/update-password','ProfileController@updatePassword')->name('update-password');
    //departments
    Route::resource('/departments', 'DepartmentController');
    Route::get('/departments/status/{id}', 'DepartmentController@status');
    //roles
    Route::resource('/roles', 'RoleController');
    Route::get('/roles/status/{id}', 'RoleController@status');
    //permissions
    Route::resource('/permissions', 'PermissionController');
    Route::get('/permissions/status/{id}', 'PermissionController@status');
    // jobtype
    Route::resource('/jobtype', 'JobTypeController');
    Route::get('/getOptions', 'JobTypeController@getOptions')->name('getOptions');
    Route::get('/getInputs', 'JobTypeController@getInputs')->name('getInputs');
    Route::get('/getTypes', 'JobTypeController@getTypes')->name('getTypes');
    Route::get('/getJobTypes', 'JobTypeController@getJobTypes')->name('getJobTypes');
    //department
    Route::resource('/departments', 'DepartmentController');
    Route::get('/departments/status/{id}', 'DepartmentController@status');
    //company
    Route::resource('/companies', 'CompanyController');
    Route::get('/company/status/{id}', 'CompanyController@status');
    Route::get('/company/portfolio/delete', 'CompanyController@deletePortfolio')->name('deletePortfolio');
    //jobs
    Route::resource('/jobs', 'JobController');
    Route::get('/job/status/{id}', 'JobController@status');
    Route::get('/getJobtype', 'JobController@departmentJobType')->name('getJobType');
    Route::get('/getStaff', 'JobController@departmentStaff')->name('getStaff');
    Route::get('/getManager', 'JobController@departmentManager')->name('getManager');
    Route::get('/completeJob', 'JobController@CompleteJob')->name('CompleteJob');
    Route::get('/assignedJob', 'JobController@AssignedJob')->name('AssignedJob');
    //job workflow
    Route::resource('/job-workflow', 'JobWorkflowController');
    //job output
    Route::resource('/job-output', 'JobOutputController');
    Route::get('/download/{id}', 'JobOutputController@getDownload');
    Route::get('/output-file/{id}', 'JobOutputController@pdfView')->name('output-file');
    //job recurrence
    Route::resource('/recurrence', 'RecurrenceController');
    // settings
    Route::resource('/settings', 'SettingController');
    Route::get('/setting/delete', 'SettingController@deleteSetting')->name('deleteSetting');
    
    // approval
    Route::resource('/approvals', 'ApprovalController');
    // invoice
    Route::resource('/invoices', 'InvoiceController');
    Route::get('/invoices-generate/{jobId}/{jobTypeWorkflow}/{workflowType}/{workflowOption}/{jobWorkflow?}','JobWorkflowController@invoiceGenerate')->name('invoices.generate');
    Route::post('/invoice/items/edit/{id}', 'InvoiceController@InvoiceItemEdit')->name('invoiceItem.edit');
    Route::get('/getJobs', 'InvoiceController@getCompanyJobs')->name('getJobs');
    Route::get('/getSettings', 'InvoiceController@getSettings')->name('getSettings');
    Route::get('/invoices/status/{id}', 'InvoiceController@status');
    Route::get('download-invoice/{id}','InvoiceController@downloadInvoice');
    Route::get('invoice-preview/{id}','InvoiceController@previewInvoice');
    Route::get('payment/{id}','InvoiceController@payment');
    Route::resource('/payments', 'PaymentController');
    // Notifications web routes
    Route::resource('/notifications', 'NotificationController');
    Route::get('notifications-{filter}', 'NotificationController@index')->name('notifications');
    Route::get('notification-markallasread', 'NotificationController@mark_all_as_read')->name('markAllRead');;
    Route::get('notification-markasread-{id}', 'NotificationController@mark_as_read');
    Route::get('notification-markasunread-{id}', 'NotificationController@mark_as_unread');
    Route::get('notification-delete-{id}', 'NotificationController@delete');
});

resources/views/layouts/navbars/auth.blade.php
<!-- Side Overlay-->
<aside id="side-overlay" class="font-size-sm">
    <!-- Side Header -->
    <div class="content-header border-bottom">
        <!-- User Avatar -->
        <a class="img-link mr-1" href="javascript:void(0)">
        </a>
        <!-- END User Avatar -->
        <!-- User Info -->
        {{-- <div class="ml-2">
            <a class="text-dark font-w600 font-size-sm" href="javascript:void(0)">Adam McCoy</a>
        </div> --}}
        <!-- END User Info -->
        <!-- Close Side Overlay -->
        <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
        <a class="ml-auto btn btn-sm btn-alt-danger" href="javascript:void(0)" data-toggle="layout"
            data-action="side_overlay_close">
            <i class="fa fa-fw fa-times"></i>
        </a>
        <!-- END Close Side Overlay -->
    </div>
    <!-- END Side Header -->
    <!-- Side Content -->
    <div class="content-side">
        <p>
            Content..
        </p>
    </div>
    <!-- END Side Content -->
</aside>
<!-- END Side Overlay -->
<!-- Header -->
<header id="page-header">
    <!-- Header Content -->
    <div class="content-header">
        <!-- Left Section -->
        <div class="d-flex align-items-center">
            <!-- Toggle Sidebar -->
            <!-- Layout API, functionality initialized in Template._uiApiLayout()-->
            <button type="button" class="btn btn-sm btn-dual mr-2 d-lg-none" data-toggle="layout"
                data-action="sidebar_toggle">
                <i class="fa fa-fw fa-bars"></i>
            </button>
            <!-- END Toggle Sidebar -->

            <!-- Toggle Mini Sidebar -->
            <!-- Layout API, functionality initialized in Template._uiApiLayout()-->
            <button type="button" class="btn btn-sm btn-dual mr-2 d-none d-lg-inline-block" data-toggle="layout"
                data-action="sidebar_mini_toggle">
                <i class="fa fa-fw fa-ellipsis-v"></i>
            </button>
            <!-- END Toggle Mini Sidebar -->            
        </div>
        <!-- END Left Section -->

        <!-- Right Section -->
        <div class="d-flex align-items-center">
            <!-- User Dropdown -->
            <div class="dropdown d-inline-block ml-2">
                <button type="button" class="btn btn-sm btn-dual d-flex align-items-center"
                    id="page-header-user-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle" src="{{ auth()->user()->img_src ? asset(auth()->user()->img_src) : asset('media/avatars/avatar10.jpg') }}" alt="Header Avatar"
                        style="width: 21px;">
                    <span class="d-none d-sm-inline-block ml-2">{{ Auth::user()->name }}</span>
                    <i class="fa fa-fw fa-angle-down d-none d-sm-inline-block ml-1 mt-1"></i>
                </button>
                <div class="dropdown-menu dropdown-menu-md dropdown-menu-right p-0 border-0"
                    aria-labelledby="page-header-user-dropdown">
                    <div class="p-3 text-center bg-primary-dark rounded-top">
                        <img class="img-avatar img-avatar48 img-avatar-thumb"
                            src="{{ auth()->user()->img_src ? asset(auth()->user()->img_src) : asset('media/avatars/avatar10.jpg') }}" alt="">
                        <p class="mt-2 mb-0 text-white font-w500">{{ ucwords(Auth::user()->name) }}</p>
                        @if(!empty(Auth::user()->getRoleNames()))
                            @foreach(Auth::user()->getRoleNames() as $role)
                                <em class="text-muted text-white-75">{{ ucwords($role) }}</em>
                            @endforeach
                        @endif
<!--                        <p class="mb-0 text-white-50 font-size-sm">{{ ucwords(Auth::user()->getRoleNames()) }}</p>-->
                    </div>
                    <div class="p-2">
                        <a class="dropdown-item d-flex align-items-center justify-content-between"
                            href="{{ route('notifications.index') }}">
                            <span class="font-size-sm font-w500">Notification</span>
                            @php
                                $unreadNotificationsCount = count(Auth::user()->unreadNotifications)
                            @endphp
                            @if ($unreadNotificationsCount == 0)
                              <i class="material-icons">0</i>
                            @else
                              <span class="notification badge badge-pill badge-primary ml-2">{{ $unreadNotificationsCount }}</span>
                            @endif                            
                        </a>
                        <a class="dropdown-item d-flex align-items-center justify-content-between"
                            href="{{ route('profile.edit',auth()->user()->id) }}">
                            <span class="font-size-sm font-w500">Profile</span>
                        </a>
                        <a href="{{ route('logout') }}"
                        class="dropdown-item d-flex align-items-center justify-content-between"
                            onclick="event.preventDefault();
                                document.getElementById('logout-form').submit();"><span class="font-size-sm font-w500">{{ __('Logout') }}</span></a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                            {{ csrf_field() }}
                        </form> 
                    </div>
                </div>
            </div>
            <!-- END User Dropdown -->

        </div>
        <!-- END Right Section -->
    </div>
    <!-- END Header Content -->

    <!-- Header Search -->
    <div id="page-header-search" class="overlay-header bg-white">
        <div class="content-header">
            <form class="w-100" action="/dashboard" method="POST">
                @csrf
                <div class="input-group">
                    <div class="input-group-prepend">
                        <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
                        <button type="button" class="btn btn-alt-danger" data-toggle="layout"
                            data-action="header_search_off">
                            <i class="fa fa-fw fa-times-circle"></i>
                        </button>
                    </div>
                    <input type="text" class="form-control" placeholder="Search or hit ESC.."
                        id="page-header-search-input" name="page-header-search-input">
                </div>
            </form>
        </div>
    </div>
    <!-- END Header Search -->

    <!-- Header Loader -->
    <!-- Please check out the Loaders page under Components category to see examples of showing/hiding it -->
    <div id="page-header-loader" class="overlay-header bg-white">
        <div class="content-header">
            <div class="w-100 text-center">
                <i class="fa fa-fw fa-circle-notch fa-spin"></i>
            </div>
        </div>
    </div>
    <!-- END Header Loader -->
</header>
<!-- END Header -->

resources/views/layouts/navbars/guest.blade.php
<nav class="w-full">
    <div class="flex py-3">
        <!-- <a class="{{ ($activePage ?? '') === 'login' ? 'text-primary' : 'text-background' }} hover:text-secondary" href="{{ route('login') }}">
            Login
        </a> -->
    </div>
</nav>

resources/views/layouts/navbars/material_sidebar.blade.php
<!-- Sidebar -->
<nav id="sidebar" aria-label="Main Navigation">
    <!-- Side Header -->
    @php
    $appSetting = \App\Models\SettingSystem::first();
    @endphp
    <div class="content-header bg-white-5">
        <!-- Logo -->
        <a class="font-w600 text-dual" href="{{ url('/') }}">
            <span class="smini-visible">
                <i class="fa fa-circle-notch text-primary"></i>
            </span>
            <span class="smini-hide font-size-h5 tracking-wider">
                {{ $appSetting ? $appSetting->name : 'khlim' }}
                {{-- <span class="font-w400"><img src="{{$appSetting ? asset($appSetting->logo) : '' }}" height="50px" width="70px" class="rounded-lg"/></span> --}}
            </span>
        </a>
        <!-- END Logo -->

        <!-- Extra -->
        <div>
            <!-- Layout API, functionality initialized in Template._uiApiLayout() -->
            <a class="d-lg-none btn btn-sm btn-dual ml-1" data-toggle="layout" data-action="sidebar_close"
                href="javascript:void(0)">
                <i class="fa fa-fw fa-times"></i>
            </a>
            <!-- END Close Sidebar -->
        </div>
        <!-- END Extra -->
    </div>
    <!-- END Side Header -->
    <!-- Sidebar Scrolling -->
    <div class="js-sidebar-scroll">
        <!-- Side Navigation -->
        <div class="content-side">
            <ul class="nav-main">
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('dashboard') ? ' active' : '' }}" href="{{ route('dashboard') }}">
                        <i class="nav-main-link-icon si si-speedometer"></i>
                        <span class="nav-main-link-name">Dashboard</span>
                    </a>
                </li>
                @can('company_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('companies','companies/*') ? ' active' : '' }}" href="{{ route('companies.index') }}">
                        <i class="nav-main-link-icon si si-user"></i>
                        <span class="nav-main-link-name">Customers</span>
                    </a>
                </li>
                @endcan
                @can('jobtype_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('jobtype','jobtype/*') ? ' active' : '' }}" href="{{ route('jobtype.index') }}">
                        <i class="nav-main-link-icon si si-cursor"></i>
                        <span class="nav-main-link-name">Job Type</span>
                    </a>
                </li>
                @endcan
                @can('jobs_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('jobs','jobs/*') ? ' active' : '' }}" href="{{ route('jobs.index') }}">
                        <i class="nav-main-link-icon fa fa-podcast"></i>
                        <span class="nav-main-link-name">Jobs</span>
                    </a>
                </li>
                @endcan
                @can('jobs_output_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('job-output','job-output/*') ? ' active' : '' }}" href="{{ route('job-output.index') }}">
                        <i class="nav-main-link-icon fa fa-outdent"></i>
                        <span class="nav-main-link-name">Jobs Output</span>
                    </a>
                </li>
                @endcan
                @can('invoice_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('invoices','invoices/*') ? ' active' : '' }}" href="{{ route('invoices.index') }}">
                        <i class="nav-main-link-icon fa fa-file-invoice"></i>
                        <span class="nav-main-link-name">Billing</span>
                    </a>
                </li>
                @endcan
                @can('recurrence_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('recurrence','recurrence/*') ? ' active' : '' }}" href="{{ route('recurrence.index') }}">
                        <i class="nav-main-link-icon fa fa-recycle"></i>
                        <span class="nav-main-link-name">Recurrence</span>
                    </a>
                </li>
                @endcan
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('notifications','notifications/*') ? ' active' : '' }}" href="{{ route('notifications.index')}}">
                        <i class="nav-main-link-icon fa fa-bell"></i>
                        <span class="nav-main-link-name">Notification
                            @php
                                $unreadNotificationsCount = count(Auth::user()->unreadNotifications)
                            @endphp
                            @if ($unreadNotificationsCount == 0)
                              {{-- <i class="material-icons">0</i> --}}
                            @else
                            <span class="badge badge-info">  <span class="notification">{{ $unreadNotificationsCount }}</span></span>
                            @endif
                        </span>
                    </a>
                </li>
                @can('approval_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('approvals','approvals/*') ? ' active' : '' }}" href="{{ route('approvals.index') }}">
                        <i class="nav-main-link-icon fa fa-universal-access"></i>
                        <span class="nav-main-link-name">Approval</span>
                    </a>
                </li>
                @endcan
                @can('department_access')
                <li class="nav-main-item"  style="margin-top:auto">
                    <a class="nav-main-link {{ request()->is('departments','departments/*') ? ' active' : '' }}" href="{{ route('departments.index') }}">
                        <i class="nav-main-link-icon fa fa-university"></i>
                        <span class="nav-main-link-name">Departments</span>
                    </a>
                </li>
                @endcan
                @can('user_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('users','users/*') ? 'active' : '' }}" href="{{ route('users.index') }}">
                        <i class="nav-main-link-icon si si-user"></i>
                        <span class="nav-main-link-name">Staff</span>
                    </a>
                </li>
                @endcan
                @hasrole(7)
                <li class="nav-main-item {{ request()->is('roles','permissions','roles/*','permissions/*') ? ' open' : '' }}">
                    <a class="nav-main-link nav-main-link-submenu" data-toggle="submenu" aria-haspopup="true" aria-expanded="true" href="#">
                        <i class="nav-main-link-icon fa fa-lock"></i>
                        <span class="nav-main-link-name">Roles</span>
                    </a>
                    <ul class="nav-main-submenu">
                        @can('role_access')
                        <li class="nav-main-item">
                            <a class="nav-main-link {{ request()->is('roles','roles/*') ? 'active' : '' }}" href="{{ route('roles.index') }}">
                                <span class="nav-main-link-name">Roles</span>
                            </a>
                        </li>
                        @endcan
                        @can('permission_access')
                        <li class="nav-main-item">
                            <a class="nav-main-link{{ request()->is('permissions','permissions/*') ? ' active' : '' }}" href="{{route('permissions.index')}}">
                                <span class="nav-main-link-name">Permission</span>
                            </a>
                        </li>
                        @endcan
                    </ul>
                </li>
               
                @endhasrole
                @can('settings_access')
                <li class="nav-main-item">
                    <a class="nav-main-link {{ request()->is('settings/*') ? ' active' : '' }}" href="{{ route('settings.create') }}">
                        <i class="nav-main-link-icon fa fa-cog"></i>
                        <span class="nav-main-link-name">Settings</span>
                    </a>
                </li>
                @endcan
              </ul>
        </div>
        <!-- END Side Navigation -->
    </div>
    <!-- END Sidebar Scrolling -->
</nav>
<!-- END Sidebar -->