routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('register', function(){
    return redirect('/login');
});
Auth::routes(['register' => false]);
Auth::routes();
Route::middleware(['auth:web'])->group(function () {
    Route::get('/', 'HomeController@index');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@index')->name('dashboard');
    //user
    Route::resource('/users', 'UserController');
    Route::get('/user/status/{id}', 'UserController@status');
    #UserProfile Routes
    Route::resource('profile','ProfileController');
    Route::post('/update-password','ProfileController@updatePassword')->name('update-password');
    //departments
    Route::resource('/departments', 'DepartmentController');
    Route::get('/departments/status/{id}', 'DepartmentController@status');
    //roles
    Route::resource('/roles', 'RoleController');
    Route::get('/roles/status/{id}', 'RoleController@status');
    //permissions
    Route::resource('/permissions', 'PermissionController');
    Route::get('/permissions/status/{id}', 'PermissionController@status');
    // jobtype
    Route::resource('/jobtype', 'JobTypeController');
    Route::get('/getOptions', 'JobTypeController@getOptions')->name('getOptions');
    Route::get('/getInputs', 'JobTypeController@getInputs')->name('getInputs');
    Route::get('/getTypes', 'JobTypeController@getTypes')->name('getTypes');
    Route::get('/getJobTypes', 'JobTypeController@getJobTypes')->name('getJobTypes');
    //department
    Route::resource('/departments', 'DepartmentController');
    Route::get('/departments/status/{id}', 'DepartmentController@status');
    //company
    Route::resource('/companies', 'CompanyController');
    Route::get('/company/status/{id}', 'CompanyController@status');
    Route::get('/company/portfolio/delete', 'CompanyController@deletePortfolio')->name('deletePortfolio');
    //jobs
    Route::resource('/jobs', 'JobController');
    Route::get('/job/status/{id}', 'JobController@status');
    Route::get('/getJobtype', 'JobController@departmentJobType')->name('getJobType');
    Route::get('/getStaff', 'JobController@departmentStaff')->name('getStaff');
    Route::get('/getManager', 'JobController@departmentManager')->name('getManager');
    Route::get('/completeJob', 'JobController@CompleteJob')->name('CompleteJob');
    Route::get('/assignedJob', 'JobController@AssignedJob')->name('AssignedJob');
    //job workflow
    Route::resource('/job-workflow', 'JobWorkflowController');
    //job output
    Route::resource('/job-output', 'JobOutputController');
    Route::get('/download/{id}', 'JobOutputController@getDownload');
    Route::get('/output-file/{id}', 'JobOutputController@pdfView')->name('output-file');
    //job recurrence
    Route::resource('/recurrence', 'RecurrenceController');
    // settings
    Route::resource('/settings', 'SettingController');
    Route::get('/setting/delete', 'SettingController@deleteSetting')->name('deleteSetting');
    
    // approval
    Route::resource('/approvals', 'ApprovalController');
    // invoice
    Route::resource('/invoices', 'InvoiceController');
    Route::get('/invoices-generate/{jobId}/{jobTypeWorkflow}/{workflowType}/{workflowOption}/{jobWorkflow?}','JobWorkflowController@invoiceGenerate')->name('invoices.generate');
    Route::post('/invoice/items/edit/{id}', 'InvoiceController@InvoiceItemEdit')->name('invoiceItem.edit');
    Route::get('/getJobs', 'InvoiceController@getCompanyJobs')->name('getJobs');
    Route::get('/getSettings', 'InvoiceController@getSettings')->name('getSettings');
    Route::get('/invoices/status/{id}', 'InvoiceController@status');
    Route::get('download-invoice/{id}','InvoiceController@downloadInvoice');
    Route::get('invoice-preview/{id}','InvoiceController@previewInvoice');
    Route::get('payment/{id}','InvoiceController@payment');
    Route::resource('/payments', 'PaymentController');
    // Notifications web routes
    Route::resource('/notifications', 'NotificationController');
    Route::get('notifications-{filter}', 'NotificationController@index')->name('notifications');
    Route::get('notification-markallasread', 'NotificationController@mark_all_as_read')->name('markAllRead');;
    Route::get('notification-markasread-{id}', 'NotificationController@mark_as_read');
    Route::get('notification-markasunread-{id}', 'NotificationController@mark_as_unread');
    Route::get('notification-delete-{id}', 'NotificationController@delete');
});

app/Http/Controllers/JobTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Jobs\JobType;
use App\Models\Users\Department;
use App\Models\Jobs\WorkflowType;
use App\Models\Jobs\WorkflowOption;
use App\Models\Jobs\JobTypeWorkflow;
use App\Models\Jobs\WorkflowNotify;
use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\DB;
use Session;
# request JobTypeStoreRequest
use App\Http\Requests\JobTypeUpdateRequest;
use App\Http\Requests\JobTypeStoreRequest;

class JobTypeController extends Controller {

    function __construct() {
        $this->middleware('permission:jobtype_access|jobtype_create|jobtype_edit|jobtype_delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:jobtype_create', ['only' => ['create', 'store']]);
        $this->middleware('permission:jobtype_edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:jobtype_delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $departmentId = auth()->user()->departments->pluck('id')->toArray();
        $jobtypes = JobType::whereIn('department_id', $departmentId)->orderBy('created_at', 'DESC')->get();
        return view('jobtypes.index', compact('jobtypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $departments = Department::where('status', 1)->get();
        $types = WorkflowType::where('status', 1)->get();
        $options = WorkflowOption::get();
        return view('jobtypes.create', compact('departments', 'types', 'options'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(JobTypeStoreRequest $request) {

        $jobType = new JobType();
        $jobType->name = $request->name;
        $jobType->department_id = $request->department_id;
        $jobType->status = 1;
        if ($jobType->save()) {
            foreach ($request->flow as $key => $status) {
                $jobTypeWorkflow = new JobTypeWorkflow();
                $jobTypeWorkflow->job_type_id = $jobType->id;
                $jobTypeWorkflow->workflow_type_id = $status['type'];
                $jobTypeWorkflow->title = $status['title'];
                $jobTypeWorkflow->save();
                // check workflow notify status
                if ($status['type'] == 3 || $status['type'] == 7 || $status['type'] == 18) {

                    $workflowNotify = new WorkflowNotify();
                    $workflowNotify->job_type_id = $jobType->id;
                    $workflowNotify->job_type_workflow_id = $jobTypeWorkflow->id;
                    $workflowNotify->workflow_type_id = $status['type'];
                    

                    if (isset($status['notify_Hours'])) {
                        $notify_hour['hours'] = $status['notify_Hours'];
                        $workflowNotify->notification_value = json_encode($notify_hour, true);
                    } elseif (isset($status['notify_Days'])) {
                        $notify_day['days'] = $status['notify_Days'];
                        $workflowNotify->notification_value = json_encode($notify_day, true);
                    }



                    if (isset($status['notifyDone'])) {
                        $workflowNotify->done_notify_day = isset($status['notifyDone']) ? $status['notifyDone'] : null;
                    } elseif (isset($status['payment'])) {
                        $workflowNotify->done_notify_day = isset($status['payment']) ? $status['payment'] : null;
                    } elseif (isset($status['adhocConsolidation'])) {
                        $workflowNotify->done_notify_day = isset($status['adhocConsolidation']) ? $status['adhocConsolidation'] : null;
                    }
                    if (isset($status['notifyNotDone'])) {
                        $workflowNotify->not_done_notify_day = isset($status['notifyNotDone']) ? $status['notifyNotDone'] : null;
                    } elseif (isset($status['adhocMBRS'])) {
                        $workflowNotify->done_notify_day = isset($status['adhocMBRS']) ? $status['adhocMBRS'] : null;
                    }
                    $workflowNotify->notify_recurrence_day = isset($status['recurrence']) ? $status['recurrence'] : 0;
                    $workflowNotify->active = isset($status['company_status_Active']) ? $status['company_status_Active'] : null;
                    $workflowNotify->semi_active = isset($status['company_status_SemiActive']) ? $status['company_status_SemiActive'] : null;
                    $workflowNotify->dormant = isset($status['company_status_Dormant']) ? $status['company_status_Dormant'] : null;
                    $workflowNotify->super_active = isset($status['company_status_SuperActive']) ? $status['company_status_SuperActive'] : null;
                    $workflowNotify->notify_account_department = isset($status['notify_account']) ? $status['notify_account'] : 0;
                    $workflowNotify->save();
                }
            }
            Session::flash('notification', 'JobType created successfully!.. ');
            Session::flash('notificationType', 'success');
            return redirect()->route('jobtype.index');
        } else {
            Session::flash('notification', 'JobType not created successfully!.. ');
            Session::flash('notificationType', 'error');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        $jobtype = JobType::with('workflows.workflow_type.workflowoption', 'workflows.workflowNotify')->find($id);
        $jobtypes = Jobtype::where('department_id', $jobtype->department_id)->get();
        return view('jobtypes.show', compact('jobtype', 'jobtypes'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $jobtype = JobType::with('workflows.workflow_type.workflowoption', 'workflows.workflowNotify')->find($id);
        $jobtypes = Jobtype::where('department_id', $jobtype->department_id)->get();
        $departments = Department::where('status', 1)->get();
        $types = WorkflowType::where('department_id', $jobtype->department_id)->where('status', 1)->get();
        $options = WorkflowOption::get();
        return view('jobtypes.edit', compact('jobtype', 'departments', 'types', 'options', 'jobtypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\JobTypeUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(JobTypeUpdateRequest $request, $id) {

        $jobtype = JobType::with('workflowtype', 'jobs')->find($id);
        if (!$jobtype->jobs->isEmpty()) {
            Session::flash('notification', 'This job type is associated with a job and cannot be edited.');
            Session::flash('notificationType', 'info');
            return redirect()->back();
        }
        $jobtype->name = $request->input('name');
        $jobtype->department_id = $request->department_id;
        if ($jobtype->update()) {

            JobTypeWorkflow::where('job_type_id', $jobtype->id)->whereNotIn('id', $request->workflow_id)->delete();
            if ($request->workflowNotify_id != null) {
                WorkflowNotify::where('job_type_id', $jobtype->id)->whereNotIn('job_type_workflow_id', $request->workflow_id)->whereNotIn('id', $request->workflowNotify_id)->delete();
            }

            foreach ($request->flow as $key => $status) {

                $typeId = $status['type'];
                if (isset($request->workflow_id[$key])) {
                    $JobTypeWorkflows = JobTypeWorkflow::find($request->workflow_id[$key]);
                    // when change workflowtype with workflownotify delete previous workflownotify
                    if (isset($JobTypeWorkflows->workflowNotify) && $JobTypeWorkflows->workflowNotify->workflow_type_id != $typeId && !in_array($typeId, [3, 7, 12, 14])) {
                        WorkflowNotify::where('job_type_id', $jobtype->id)->where('job_type_workflow_id', $JobTypeWorkflows->workflowNotify->job_type_workflow_id)->delete();
                        $JobTypeWorkflows = JobTypeWorkflow::find($request->workflow_id[$key]);
                    }
                } else {
                    $JobTypeWorkflows = new JobTypeWorkflow();
                }
                $JobTypeWorkflows->job_type_id = $jobtype->id;
                $JobTypeWorkflows->workflow_type_id = $typeId;
                $JobTypeWorkflows->title = $status['title'];
                $JobTypeWorkflows->save();
                // check workflow status notify
                if ($status['type'] == 3 || $status['type'] == 7 || $status['type'] == 18) {
                    if (isset($JobTypeWorkflows->workflowNotify)) {
                        $workflowNotify = WorkflowNotify::find($JobTypeWorkflows->workflowNotify->id);
                        if (!isset($status['notify_Hours'])) {

                            $workflowNotify->notification_value = null;
                        } elseif (!isset($status['notify_Days'])) {

                            $workflowNotify->notification_value = null;
                        }
                        if (!isset($status['notifyDone'])) {
                            $workflowNotify->done_notify_day = isset($status['notifyDone']) ? $status['notifyDone'] : null;
                        } elseif (!isset($status['payment'])) {

resources/views/jobtypes/index.blade.php
@extends('layouts.app', [
'activePage' => 'jobtype-list',
'menuParent' => 'jobtype-list',
'title' => 'JobType',
])
@section('content')
<!-- Hero -->
<div class="bg-body-light">
    <div class="content content-full">
        <div class="row d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <div class="col-sm-8 d-flex justify-content-start align-items-center">
                <h1 class="flex-sm-00-auto h3 my-2">
                    {{__('Job Type')}} <small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted"></small>
                </h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">Job Type</li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="text-black text-muted">{{__('List')}}</a>
                        </li>
                    </ol>
                </nav>
            </div>
            <div class="col-sm-4">
                @can('jobtype_create')
                <div class="text-right">
                    <a href="{{ route('jobtype.create') }}" class="btn btn-primary">Create</a>
                </div>
                @endcan
            </div>
        </div>
    </div>
</div>
<!-- END Hero -->
<!-- Page Content -->
<div class="content">
    <!-- Dynamic Table with Export Buttons -->
    <div class="block block-rounded">
        <div class="block-content block-content-full">
            <!-- DataTables init on table by adding .js-dataTable-buttons class, functionality is initialized in js/pages/tables_datatables.js -->
            <table class="table table-bordered table-striped table-vcenter js-dataTable-full   font-size-sm">
                <thead>
                    <tr>
                        <th class="text-left" style="width: 80px;">#</th>
                        <th>Title</th>
                        <th>Department</th>
                        <th>Created</th>
                        <th>Modified</th>
                        <th class="text-center">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($jobtypes as $key => $jobtype)
                    <tr>
                        <td class="text-left">{{ $key +1 }}</td>
                        <td class="font-w600">
                            <a href="{{ route('jobtype.show',$jobtype->id) }}">{{ ucwords($jobtype->name) }}</a>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <span class="text-muted">{{ ucwords($jobtype->department->name) }}</span>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <span class="text-muted">{{ Carbon\Carbon::parse($jobtype->created_at)->format('d-m-Y') }}</span>
                        </td>
                        <td class="d-none d-sm-table-cell">
                            <span class="text-muted">{{ Carbon\Carbon::parse($jobtype->updated_at)->format('d-m-Y')}}</span>
                        </td>

                        <td class="text-center">
                            <div class="btn-group">
                                @can('jobtype_edit')
                                <a href="{{ route('jobtype.edit',$jobtype->id) }}" class="btn btn-sm btn-light" ><i class="fa fa-edit"></i></a>
                                @endcan
                                @can('jobtype_delete')
                                <form action="{{ route('jobtype.destroy',$jobtype->id) }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-sm btn-light delete" data-name="{{ $jobtype->name }}"
                                            title="{{__('Delete')}}">
                                        <i class="fa fa-trash"></i>
                                    </button>
                                </form>
                                @endcan
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <!-- END Dynamic Table with Export Buttons -->
</div>
<!-- END Page Content -->
@endsection

resources/views/jobtypes/show.blade.php
@extends('layouts.app', [
'activePage' => 'JobType-show',
'menuParent' => 'JobType-show',
'title' => 'JobType Show',
])
@section('content')
<div class="bg-body-light">
    <div class="content content-full">
        <div class="row d-flex flex-column flex-sm-row justify-content-sm-between align-items-sm-center">
            <div class="col-sm-12 d-flex justify-content-start align-items-center">
                <h1 class="flex-sm-00-auto h3 my-2">
                    {{__('Job Type')}} <small class="d-block d-sm-inline-block mt-2 mt-sm-0 font-size-base font-w400 text-muted"></small>
                </h1>
                <nav class="flex-sm-00-auto ml-sm-3" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ route('jobtype.index') }}">Job Type</a></li>
                        <li class="breadcrumb-item" aria-current="page">
                            <a class="text-black text-muted">{{__('Details')}}</a>
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- Page Content -->
<div class="content w-100">
    <div class="block block-rounded">
        <ul class="nav nav-tabs nav-tabs-block" data-toggle="tabs" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" href="#btabs-home">General</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#btabs-workflow">
                    Work Flow
                </a>
            </li>
        </ul>
        <div class="block-content tab-content">
            <div class="tab-pane active" id="btabs-home" role="tabpanel">
                <div class="block-content block-content-full ml-12 ">
                    <div class="row">
                        <div class="col-md-6">
                            <dt>{{ __('JobType Name') }}</dt>
                            <dd>{{ucwords($jobtype->name)}}</dd>
                        </div>
                        <div class="col-md-6">
                            <dt>{{ __('Department') }}</dt>
                            <dd>{{ucwords($jobtype->department->name) }}</dd>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="btabs-workflow" role="tabpanel">
                <div class="row">
                    <div class="col-lg-12">
                        <div id="inputFormRow">
                            @foreach($jobtype->workflows as $key => $workflow)
                            <div class="row">
                                <div class="col-md-4">
                                    <dd><label>{{$key+1}}. Title: </label> {{ucwords($workflow->title)}}</dd>
                                </div>
                                <div class="col-md-4">
                                    <dd><label>Type: </label> {{ucwords($workflow->workflow_type->name)}}</dd>
                                </div>
                                <div class="col-md-4">
                                    <dd> <label>Option: </label>
                                        @foreach($workflow->workflow_type->workflowoption as $key => $option)
                                        {{ ucwords($option->options) }}@if($loop->last) @else {{__(',') }} @endif
                                        @endforeach
                                    </dd>
                                </div>  
                            </div><!-- /.row -->
                            @if($workflow->workflowNotify)

                            @if($workflow->workflow_type_id == 3 || $workflow->workflow_type_id == 7 || $workflow->workflow_type_id == 18)
                            @php
                            $span = $workflow->workflow_type_id == 3 ? 'Hours':'Days';
                            @endphp
                            <div class="row add py-1">
                                <div class="col-md-4 offset-4">
                                    @php
                                    $notify = json_decode($workflow->workflowNotify->notification_value);
                                    $value = $workflow->workflow_type_id == 3 ? $notify->hours : $notify->days;
                                    @endphp
                                    <label> Notify,If more than</label></div><div class="col-md-4">{{($value !== NULL)?$value:'N/A '}} {{$span}}
                                </div>
                            </div>
                            @endif
                            @endif
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END Page Content -->
@endsection